### ISSUE TITLE
Transfer Tree plot for Hclust recipe to StatPlots

### ISSUE THREAD

**Issue by piever** [BioJulia/Microbiome.jl#19]
After a lengthy discussion on slack, it seems that StatPlots will not be afraid to take dependencies to support visualizations for types in the soon to be revamped [Stats](https://github.com/JuliaStats/Stats.jl) metapackage. The Tree plot for Hclust recipe by @kescobo is an example of that and I wanted to ask if there is consensus to move it to StatPlots (I for one am in favor). I think Microbiome is a bit of an odd place for the recipe as it could hurt discoverability (many people do clustering without necessarily working with Microbiome data).

cc: @mkborregaard

**Comment by mkborregaard** [comment]
I'm in favour too!

**Comment by kescobo** [comment]
Hmm - looks like images aren't getting generated in my docs, but the idea of leaf ordering is:

```
julia> using Microbiome, Clustering

julia> dm = [0. .1 .2
                    .1 0. .15
                    .2 .15 0.];

julia> h = hclust(dm, :single);

julia> h.labels = ["a", "b", "c"];

julia> hclustplot(h)
```

![screen shot 2018-05-17 at 14 09 07](https://user-images.githubusercontent.com/3502975/40195661-207efc3a-59dc-11e8-9099-bbbca0ed6f54.png)

This is a valid tree, but b is actually more similar to c, so it's nicer if they're ordered next to each other:

```
julia> optimalorder!(h, dm)

julia> hclustplot(h)
```

![screen shot 2018-05-17 at 14 09 19](https://user-images.githubusercontent.com/3502975/40195678-2f1922de-59dc-11e8-9730-c98b2732fb6c.png)

**Comment by piever** [comment]
I'm probably unable to review your code on this one as I don't know the algorithm, but if you can also add a test that you get the same results as your reference paper I'd be happy to include it. It wouldn't be the first time that we write an algorithm that's mainly useful for visualization in a plotting package (for example @mkborregaard wrote code to compute optimal bin number in 2D histograms).

**Comment by kescobo** [comment]
@piever Ahh, good to know, thanks! Probably won't get to it for a couple of weeks, but I will definitely work on it since that's the place it makes the most sense for sure.

**Comment by mkborregaard** [comment]
Sounds great.
