### ISSUE TITLE
Documentation code examples broken

### ISSUE THREAD

**Issue by mschauer** [BioJulia/Microbiome.jl#28]
https://biojulia.net/Microbiome.jl/latest/abundances.html

Apparently some missing packages.

**Comment by kescobo** [comment]
Thanks for the heads up @mschauer - I haven't fixed the documentation in a while. Now that we can do doc-specific dependencies, this should be pretty easy to fix I would think.

**Comment by mschauer** [comment]
"heads up" is the right word, this is exactly as it was meant.
