### ISSUE TITLE
Add prevalence and abundance filters to AbundanceTable

### ISSUE THREAD

**Issue by kescobo** [BioJulia/Microbiome.jl#32]
Should have a way to get views of an `AbundanceTable` (`ComMatrix`) with only samples that have a given abundance of feature X, or only have features that meet a minimum threshold of prevalence (where prevalence can be defined with a lower bound).

@mkborregaard is this something you'd like to have in `SpatialEcology`? I can do it there and import here, or just implement it here.

**Comment by mkborregaard** [comment]
This should already exist with the `view` method on `ComMatrix`?

**Comment by kescobo** [comment]
I was thinking of an interface along the lines of

```
filtered_cm = prevalence_filter(cm, 0.001)
```

I would definitely define it using the `view` method, just want some additional convenience as I find myself doing stuff like this a lot. I can just implement it here and you can take a look, then if it seems useful I can port it over - shouldn't be particularly complex.

**Comment by mkborregaard** [comment]
Something like 
```julia
prevalence_filter(cm::ComMatrix, level) = view(cm, species = prevalence(cm) .> level)
```
?

**Comment by kescobo** [comment]
Yeah, exactly. And I have `prevalence` defined where I can set a lower bound on what counts as present, [see here](https://github.com/BioJulia/Microbiome.jl/blob/master/src/abundances.jl#L88-L97).
