### ISSUE TITLE
Broken link to biojulia contribution guidelines

### ISSUE THREAD

**Issue by EvoArt** [BioJulia/Microbiome.jl#69]
The link in the docs to the biojulia contributors guidelines is broken

**Comment by kescobo** [comment]
Good point - Should maybe point here: https://biojulia.net/#Community

The repo itself also has https://github.com/BioJulia/Microbiome.jl/blob/main/CONTRIBUTING.md, but there's a bunch bitrot in the BioJulia community stuff (eg website, guidelines). It's on my / @jakobnissen / @BenJWard 's list, but there's a lot of other stuff to do :facepalm: 

@annelle-abatoni or @anikaluo can you just remove that sentence or point it to the CONTRIBUTING.md here and on BiobakeryUtils.jl?

**Comment by kescobo** [comment]
Closed by #73
